CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(100),
  "capabilities_json" text
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(255),
  "status" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "student_code" varchar(50),
  "school_level" varchar(50)
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "main_subject_id" int,
  "years_experience" int,
  "degree" varchar(255)
);

CREATE TABLE "staffs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "department" varchar(120),
  "position" varchar(120)
);

CREATE TABLE "admins" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "super_admin" boolean
);

CREATE TABLE "subjects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "slug" varchar(120) UNIQUE NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_id" int NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "duration_weeks" int,
  "price" decimal(12,2),
  "is_online" boolean
);

CREATE TABLE "classes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255),
  "teacher_id" int,
  "ta_id" int,
  "modality" varchar(20),
  "capacity" int,
  "visibility" varchar(20),
  "created_at" datetime
);

CREATE TABLE "class_meetings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "meeting_no" int,
  "start_at" datetime,
  "end_at" datetime,
  "online_link" varchar(500)
);

CREATE TABLE "enrollments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "student_id" int NOT NULL,
  "enrolled_at" datetime,
  "status" varchar(20)
);

CREATE TABLE "attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "meeting_id" int NOT NULL,
  "enrollment_id" int NOT NULL,
  "status" varchar(20),
  "checkin_at" datetime,
  "note" varchar(255)
);

CREATE TABLE "skills" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(40) UNIQUE NOT NULL,
  "name" varchar(120) NOT NULL
);

CREATE TABLE "course_components" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "skill_id" int,
  "name" varchar(120),
  "sort_order" int,
  "weight_percent" decimal(5,2)
);

CREATE TABLE "grade_component_aggregates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" int NOT NULL,
  "course_component_id" int NOT NULL,
  "total_score" decimal(8,2),
  "last_calculated_at" datetime
);

CREATE TABLE "materials" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "type" varchar(30),
  "file_url" varchar(500),
  "can_download" boolean,
  "tags" varchar(255),
  "created_at" datetime,
  "class_id" int,
  "course_id" int,
  "course_component_id" int
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "provider" varchar(50),
  "video_url" varchar(500) NOT NULL,
  "duration_sec" int,
  "created_at" datetime,
  "class_id" int,
  "meeting_id" int,
  "course_component_id" int
);

CREATE TABLE "video_access_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "video_id" int NOT NULL,
  "user_id" int NOT NULL,
  "played_at" datetime,
  "seconds_watched" int,
  "device_fingerprint" varchar(120),
  "ip" varchar(64)
);

CREATE TABLE "assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "created_by" int NOT NULL,
  "course_component_id" int,
  "title" varchar(255) NOT NULL,
  "type" varchar(20),
  "open_at" datetime,
  "due_at" datetime,
  "max_score" decimal(8,2),
  "attachments_json" text,
  "created_at" datetime
);

CREATE TABLE "submissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" int NOT NULL,
  "enrollment_id" int NOT NULL,
  "submitted_at" datetime,
  "text_answer" text,
  "file_url" varchar(500),
  "status" varchar(20),
  "late_seconds" int
);

CREATE TABLE "grades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "submission_id" int UNIQUE NOT NULL,
  "grader_id" int NOT NULL,
  "score" decimal(8,2),
  "feedback" text,
  "graded_at" datetime
);

CREATE TABLE "grade_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "name" varchar(120) NOT NULL,
  "weight" decimal(6,3),
  "drop_lowest" boolean
);

CREATE TABLE "grade_aggregates" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" int UNIQUE NOT NULL,
  "total_score" decimal(8,2),
  "last_calculated_at" datetime
);

CREATE TABLE "audit_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action" varchar(100) NOT NULL,
  "entity" varchar(100),
  "entity_id" int,
  "meta_json" text,
  "created_at" datetime
);

CREATE TABLE "site_settings" (
  "key" varchar(120) PRIMARY KEY,
  "value" text,
  "description" varchar(255)
);

CREATE UNIQUE INDEX ON "enrollments" ("class_id", "student_id");

CREATE UNIQUE INDEX ON "attendance" ("meeting_id", "enrollment_id");

CREATE UNIQUE INDEX ON "grade_component_aggregates" ("enrollment_id", "course_component_id");

CREATE UNIQUE INDEX ON "submissions" ("assignment_id", "enrollment_id");

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "students" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "teachers" ADD FOREIGN KEY ("main_subject_id") REFERENCES "subjects" ("id");

ALTER TABLE "staffs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "admins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("subject_id") REFERENCES "subjects" ("id");

ALTER TABLE "classes" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "classes" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "classes" ADD FOREIGN KEY ("ta_id") REFERENCES "users" ("id");

ALTER TABLE "class_meetings" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");

ALTER TABLE "attendance" ADD FOREIGN KEY ("meeting_id") REFERENCES "class_meetings" ("id");

ALTER TABLE "attendance" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id");

ALTER TABLE "course_components" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "course_components" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "grade_component_aggregates" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id");

ALTER TABLE "grade_component_aggregates" ADD FOREIGN KEY ("course_component_id") REFERENCES "course_components" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "materials" ADD FOREIGN KEY ("course_component_id") REFERENCES "course_components" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("meeting_id") REFERENCES "class_meetings" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("course_component_id") REFERENCES "course_components" ("id");

ALTER TABLE "video_access_logs" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id");

ALTER TABLE "video_access_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "assignments" ADD FOREIGN KEY ("course_component_id") REFERENCES "course_components" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id");

ALTER TABLE "submissions" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id");

ALTER TABLE "grades" ADD FOREIGN KEY ("submission_id") REFERENCES "submissions" ("id");

ALTER TABLE "grades" ADD FOREIGN KEY ("grader_id") REFERENCES "users" ("id");

ALTER TABLE "grade_items" ADD FOREIGN KEY ("class_id") REFERENCES "classes" ("id");

ALTER TABLE "grade_aggregates" ADD FOREIGN KEY ("enrollment_id") REFERENCES "enrollments" ("id");

ALTER TABLE "audit_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
