-- =================================================================
-- DMT EDUCATION SYSTEM DATABASE - SCHEMA DEFINITION
-- =================================================================
--
-- File này chỉ tạo cấu trúc database (tables, indexes, foreign keys)
-- Sau khi chạy file này, vui lòng chạy Db_DMT_Setup.sql để:
--   + Cài đặt functions, triggers, procedures
--   + Insert dữ liệu mẫu
--
-- =================================================================
-- HƯỚNG DẪN CÀI ĐẶT:
-- 1. Chạy file này: psql -U postgres -f Db_DMT.sql
-- 2. Chạy setup file: psql -U postgres -f Db_DMT_Setup.sql
-- =================================================================

-- Tạo database
CREATE DATABASE dmt_education_system
WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    TEMPLATE template0;

-- Thiết lập parameter 
ALTER DATABASE dmt_education_system SET timezone TO 'Asia/Ho_Chi_Minh';
COMMENT ON DATABASE dmt_education_system IS 'Database for DMT Education Management System - University Project';

-- Kết nối database
\c dmt_education_system;

-- Tạo extension cần thiết 
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- BẢNG CORE - QUẢN LÝ NGƯỜI DÙNG
-- =================================================================

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "full_name" varchar(255) NOT NULL,
  "phone" varchar(20),
  "address" text,
  "birth_date" date,
  "avatar_url" varchar(500),
  "status" boolean DEFAULT true,
  "last_login_at" timestamp,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "students" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "student_code" varchar(50) UNIQUE,
  "school_level" varchar(50), -- elementary, middle_school, high_school
  "parent_name" varchar(255),
  "parent_phone" varchar(20),
  "parent_email" varchar(255),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "teachers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "teacher_code" varchar(50) UNIQUE,
  "main_subject_id" int,
  "years_experience" int DEFAULT 0,
  "degree" varchar(255),
  "specialization" varchar(255),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "staff" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE NOT NULL,
  "staff_code" varchar(50) UNIQUE,
  "department" varchar(120),
  "position" varchar(120),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG QUẢN LÝ HỌC VỤ
-- =================================================================

CREATE TABLE "subjects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_id" int NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "duration_weeks" int DEFAULT 12,
  "total_sessions" int DEFAULT 24,
  "price" decimal(12,2),
  "level" varchar(20) DEFAULT 'beginner', -- beginner, intermediate, advanced
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "classes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" int NOT NULL,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(255) NOT NULL,
  "teacher_id" int NOT NULL,
  "capacity" int DEFAULT 25,
  "current_students" int DEFAULT 0,
  "start_date" date,
  "end_date" date,
  "schedule_days" varchar(50), -- "Monday,Wednesday,Friday"
  "schedule_time" varchar(20), -- "18:00-20:00"
  "classroom" varchar(100),
  "status" varchar(20) DEFAULT 'planning', -- planning, active, completed, cancelled
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "class_sessions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "session_number" int NOT NULL,
  "title" varchar(255),
  "session_date" date NOT NULL,
  "start_time" time NOT NULL,
  "end_time" time NOT NULL,
  "content" text,
  "homework" text,
  "status" varchar(20) DEFAULT 'scheduled', -- scheduled, completed, cancelled
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG QUẢN LÝ ĐĂNG KÝ & ĐIỂM DANH
-- =================================================================

CREATE TABLE "enrollments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "student_id" int NOT NULL,
  "enrollment_date" date DEFAULT CURRENT_DATE,
  "status" varchar(20) DEFAULT 'active', -- active, completed, dropped, suspended
  "payment_status" varchar(20) DEFAULT 'pending', -- pending, paid, partial, overdue
  "total_fee" decimal(12,2),
  "paid_amount" decimal(12,2) DEFAULT 0,
  "discount_percent" decimal(5,2) DEFAULT 0,
  "notes" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "attendance" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" int NOT NULL,
  "enrollment_id" int NOT NULL,
  "status" varchar(20) DEFAULT 'absent', -- present, absent, late, excused
  "check_in_time" timestamp,
  "notes" text,
  "marked_by" int, -- teacher/staff who marked
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG QUẢN LÝ BÀI TẬP & ĐIỂM SỐ (ĐƠN GIẢN)
-- =================================================================

CREATE TABLE "assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "due_date" date,
  "max_score" decimal(6,2) DEFAULT 100,
  "assignment_type" varchar(30) DEFAULT 'homework', -- homework, quiz, exam, project
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "submissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assignment_id" int NOT NULL,
  "student_id" int NOT NULL,
  "content" text,
  "file_url" varchar(500),
  "submitted_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "is_late" boolean DEFAULT false
);

CREATE TABLE "grades" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "submission_id" int UNIQUE NOT NULL,
  "score" decimal(6,2),
  "feedback" text,
  "graded_by" int NOT NULL,
  "graded_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG QUẢN LÝ TÀI LIỆU & THÔNG BÁO (ĐƠN GIẢN)
-- =================================================================

CREATE TABLE "materials" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "file_url" varchar(500),
  "file_type" varchar(50), -- pdf, doc, video, image, link
  "file_size" bigint,
  "is_downloadable" boolean DEFAULT true,
  "uploaded_by" int NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text NOT NULL,
  "type" varchar(50) DEFAULT 'general', -- general, assignment, grade, payment, system
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG THANH TOÁN (ĐƠN GIẢN)
-- =================================================================

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "enrollment_id" int NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "payment_method" varchar(50) DEFAULT 'cash', -- cash, bank_transfer, online
  "payment_date" date DEFAULT CURRENT_DATE,
  "receipt_number" varchar(100),
  "notes" text,
  "processed_by" int,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG KHẢO SÁT (ĐƠN GIẢN CHO ĐỒ ÁN)
-- =================================================================

CREATE TABLE "surveys" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int,
  "title" varchar(255) NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_by" int NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "survey_questions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_id" int NOT NULL,
  "question_text" text NOT NULL,
  "question_type" varchar(20) DEFAULT 'text', -- text, rating, multiple_choice
  "options" text, -- JSON for multiple choice options
  "is_required" boolean DEFAULT false,
  "order_number" int DEFAULT 1
);

CREATE TABLE "survey_responses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_id" int NOT NULL,
  "student_id" int NOT NULL,
  "question_id" int NOT NULL,
  "answer_text" text,
  "answer_rating" int,
  "submitted_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- BẢNG AUDIT LOG (ĐƠN GIẢN)
-- =================================================================

CREATE TABLE "activity_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "action" varchar(100) NOT NULL,
  "table_name" varchar(100),
  "record_id" int,
  "description" text,
  "ip_address" inet,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- CÀI ĐẶT HỆ THỐNG
-- =================================================================

CREATE TABLE "system_settings" (
  "key" varchar(100) PRIMARY KEY,
  "value" text,
  "description" text,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =================================================================
-- TẠO INDEX (CHỈ NHỮNG CÁI CẦN THIẾT)
-- =================================================================

-- Users indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_users_status ON users(status);

-- Classes & Enrollments
CREATE INDEX idx_classes_teacher ON classes(teacher_id);
CREATE INDEX idx_classes_course ON classes(course_id);
CREATE INDEX idx_classes_status ON classes(status);
CREATE INDEX idx_enrollments_class ON enrollments(class_id);
CREATE INDEX idx_enrollments_student ON enrollments(student_id);

-- Attendance & Grades
CREATE INDEX idx_attendance_session ON attendance(session_id);
CREATE INDEX idx_attendance_enrollment ON attendance(enrollment_id);
CREATE INDEX idx_grades_submission ON grades(submission_id);

-- Notifications
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read);

-- =================================================================
-- RÀNG BUỘC UNIQUE
-- =================================================================

CREATE UNIQUE INDEX ON enrollments (class_id, student_id);
CREATE UNIQUE INDEX ON attendance (session_id, enrollment_id);
CREATE UNIQUE INDEX ON submissions (assignment_id, student_id);

-- =================================================================
-- THIẾT LẬP FOREIGN KEY
-- =================================================================

-- Users relationships
ALTER TABLE users ADD FOREIGN KEY (role_id) REFERENCES roles (id);
ALTER TABLE students ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE teachers ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE teachers ADD FOREIGN KEY (main_subject_id) REFERENCES subjects (id);
ALTER TABLE staff ADD FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- Course relationships
ALTER TABLE courses ADD FOREIGN KEY (subject_id) REFERENCES subjects (id);
ALTER TABLE classes ADD FOREIGN KEY (course_id) REFERENCES courses (id);
ALTER TABLE classes ADD FOREIGN KEY (teacher_id) REFERENCES teachers (id);

-- Session relationships
ALTER TABLE class_sessions ADD FOREIGN KEY (class_id) REFERENCES classes (id) ON DELETE CASCADE;

-- Enrollment relationships
ALTER TABLE enrollments ADD FOREIGN KEY (class_id) REFERENCES classes (id);
ALTER TABLE enrollments ADD FOREIGN KEY (student_id) REFERENCES students (id);
ALTER TABLE attendance ADD FOREIGN KEY (session_id) REFERENCES class_sessions (id);
ALTER TABLE attendance ADD FOREIGN KEY (enrollment_id) REFERENCES enrollments (id);
ALTER TABLE attendance ADD FOREIGN KEY (marked_by) REFERENCES users (id);

-- Assignment relationships
ALTER TABLE assignments ADD FOREIGN KEY (class_id) REFERENCES classes (id);
ALTER TABLE assignments ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE submissions ADD FOREIGN KEY (assignment_id) REFERENCES assignments (id);
ALTER TABLE submissions ADD FOREIGN KEY (student_id) REFERENCES students (id);
ALTER TABLE grades ADD FOREIGN KEY (submission_id) REFERENCES submissions (id);
ALTER TABLE grades ADD FOREIGN KEY (graded_by) REFERENCES users (id);

-- Material relationships
ALTER TABLE materials ADD FOREIGN KEY (class_id) REFERENCES classes (id);
ALTER TABLE materials ADD FOREIGN KEY (uploaded_by) REFERENCES users (id);

-- Notification relationships
ALTER TABLE notifications ADD FOREIGN KEY (user_id) REFERENCES users (id);

-- Payment relationships
ALTER TABLE payments ADD FOREIGN KEY (enrollment_id) REFERENCES enrollments (id);
ALTER TABLE payments ADD FOREIGN KEY (processed_by) REFERENCES users (id);

-- Survey relationships
ALTER TABLE surveys ADD FOREIGN KEY (class_id) REFERENCES classes (id);
ALTER TABLE surveys ADD FOREIGN KEY (created_by) REFERENCES users (id);
ALTER TABLE survey_questions ADD FOREIGN KEY (survey_id) REFERENCES surveys (id) ON DELETE CASCADE;
ALTER TABLE survey_responses ADD FOREIGN KEY (survey_id) REFERENCES surveys (id);
ALTER TABLE survey_responses ADD FOREIGN KEY (student_id) REFERENCES students (id);
ALTER TABLE survey_responses ADD FOREIGN KEY (question_id) REFERENCES survey_questions (id);

-- Log relationships
ALTER TABLE activity_logs ADD FOREIGN KEY (user_id) REFERENCES users (id);

-- =================================================================
-- CHÚ Ý: TRIGGERS, FUNCTIONS VÀ DỮ LIỆU MẪU
-- =================================================================
-- Để cài đặt các trigger, function, procedure và insert dữ liệu mẫu,
-- vui lòng chạy file Db_DMT_Setup.sql sau khi tạo database này.



-- =================================================================
-- COMMENTS MÔ TẢ
-- =================================================================

COMMENT ON TABLE roles IS 'Bảng vai trò người dùng';
COMMENT ON TABLE users IS 'Bảng thông tin người dùng chính';
COMMENT ON TABLE students IS 'Bảng thông tin học sinh';
COMMENT ON TABLE teachers IS 'Bảng thông tin giáo viên';
COMMENT ON TABLE staff IS 'Bảng thông tin nhân viên';
COMMENT ON TABLE subjects IS 'Bảng môn học';
COMMENT ON TABLE courses IS 'Bảng khóa học';
COMMENT ON TABLE classes IS 'Bảng lớp học';
COMMENT ON TABLE class_sessions IS 'Bảng buổi học của lớp';
COMMENT ON TABLE enrollments IS 'Bảng đăng ký học';
COMMENT ON TABLE attendance IS 'Bảng điểm danh';
COMMENT ON TABLE assignments IS 'Bảng bài tập';
COMMENT ON TABLE submissions IS 'Bảng nộp bài';
COMMENT ON TABLE grades IS 'Bảng điểm số';
COMMENT ON TABLE materials IS 'Bảng tài liệu học tập';
COMMENT ON TABLE notifications IS 'Bảng thông báo';
COMMENT ON TABLE payments IS 'Bảng thanh toán';
COMMENT ON TABLE surveys IS 'Bảng khảo sát';
COMMENT ON TABLE activity_logs IS 'Bảng nhật ký hoạt động';
COMMENT ON TABLE system_settings IS 'Bảng cài đặt hệ thống';

-- =================================================================
-- KẾT THÚC SCRIPT
-- =================================================================

