-- =====================================================================
-- INSERT CLASSES FROM SCHEDULE DATA
-- Thêm dữ liệu lịch học từ scheduleData.ts vào database
-- =====================================================================

USE DMT_Education;
GO

-- Note: Cần đảm bảo đã có COURSES và TEACHERS trong database trước
-- File này giả định:
-- - COURSE_ID 1-10 đã tồn tại
-- - TEACHER_ID 1-15 đã tồn tại

-- ============ GÒ VẤP CAMPUS ============

-- IELTS Intensive - Foundation
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (1, 'IELTS-GV-01', N'IELTS Intensive - Foundation', 1, 20, 17, '2025-01-15', '2025-03-15', 'MONDAY,WEDNESDAY,FRIDAY', '18:30-20:30', N'P.201 - Tầng 2 - Gò Vấp', 'ACTIVE');

-- IELTS Target 7.0+
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (1, 'IELTS-GV-02', N'IELTS Target 7.0+', 2, 15, 12, '2025-01-20', '2025-03-20', 'TUESDAY,THURSDAY,SATURDAY', '19:00-21:00', N'P.305 - Tầng 3 - Gò Vấp', 'ACTIVE');

-- Toán Tư duy THCS
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (2, 'MATH-GV-01', N'Toán Tư duy THCS', 3, 25, 22, '2025-01-18', '2025-03-18', 'TUESDAY,THURSDAY,SATURDAY', '17:00-19:00', N'P.102 - Tầng 1 - Gò Vấp', 'ACTIVE');

-- Toán THPT - Luyện thi THPT QG
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (2, 'MATH-GV-02', N'Toán THPT - Luyện thi THPT QG', 4, 20, 18, '2025-01-15', '2025-04-15', 'MONDAY,WEDNESDAY,SUNDAY', '19:30-21:30', N'P.401 - Tầng 4 - Gò Vấp', 'ACTIVE');

-- Văn THCS - Nâng cao kỹ năng viết
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (3, 'VAN-GV-01', N'Văn THCS - Nâng cao kỹ năng viết', 5, 18, 14, '2025-01-22', '2025-03-22', 'MONDAY,WEDNESDAY', '18:00-20:00', N'P.203 - Tầng 2 - Gò Vấp', 'ACTIVE');

-- ============ TÂN BÌNH CAMPUS ============

-- Lập trình Junior - Python Foundation
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (4, 'CODE-TB-01', N'Lập trình Junior - Python Foundation', 6, 15, 13, '2025-01-20', '2025-04-20', 'TUESDAY,THURSDAY', '19:00-21:00', N'Lab 1 - Tầng 3 - Tân Bình', 'ACTIVE');

-- Lập trình Web - HTML/CSS/JavaScript
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (4, 'CODE-TB-02', N'Lập trình Web - HTML/CSS/JavaScript', 7, 18, 16, '2025-01-15', '2025-04-15', 'MONDAY,WEDNESDAY,FRIDAY', '18:30-20:30', N'Lab 2 - Tầng 3 - Tân Bình', 'ACTIVE');

-- Tiếng Việt nâng cao THPT
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (3, 'VAN-TB-01', N'Tiếng Việt nâng cao THPT', 8, 20, 15, '2025-01-20', '2025-04-20', 'MONDAY,WEDNESDAY,FRIDAY', '17:30-19:30', N'P.205 - Tầng 2 - Tân Bình', 'ACTIVE');

-- English Communication - Business
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (1, 'ENG-TB-01', N'English Communication - Business', 9, 15, 11, '2025-01-18', '2025-03-18', 'TUESDAY,THURSDAY,SATURDAY', '18:00-20:00', N'P.302 - Tầng 3 - Tân Bình', 'ACTIVE');

-- Toán tư duy sáng tạo Tiểu học
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (2, 'MATH-TB-01', N'Toán tư duy sáng tạo Tiểu học', 10, 20, 18, '2025-01-25', '2025-03-25', 'SATURDAY,SUNDAY', '08:30-10:30', N'P.101 - Tầng 1 - Tân Bình', 'ACTIVE');

-- ============ THỦ ĐỨC CAMPUS ============

-- Khoa học tự nhiên - Vật lý THPT
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (5, 'PHY-TD-01', N'Khoa học tự nhiên - Vật lý THPT', 11, 18, 14, '2025-01-25', '2025-04-25', 'MONDAY,WEDNESDAY', '18:00-20:00', N'Lab Vật lý - Tầng 2 - Thủ Đức', 'ACTIVE');

-- Hóa học THPT - Nâng cao
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (5, 'CHEM-TD-01', N'Hóa học THPT - Nâng cao', 12, 16, 13, '2025-01-22', '2025-04-22', 'TUESDAY,THURSDAY,SATURDAY', '19:00-21:00', N'Lab Hóa - Tầng 3 - Thủ Đức', 'ACTIVE');

-- IELTS Junior - Khởi đầu tự tin
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (1, 'IELTS-TD-01', N'IELTS Junior - Khởi đầu tự tin', 13, 20, 16, '2025-01-25', '2025-04-25', 'TUESDAY,THURSDAY,SATURDAY', '16:00-18:00', N'P.401 - Tầng 4 - Thủ Đức', 'ACTIVE');

-- Sinh học THPT - Ôn thi THPT QG
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (5, 'BIO-TD-01', N'Sinh học THPT - Ôn thi THPT QG', 14, 18, 15, '2025-01-20', '2025-04-20', 'MONDAY,WEDNESDAY,SUNDAY', '18:30-20:30', N'P.205 - Tầng 2 - Thủ Đức', 'ACTIVE');

-- English for Kids - Tiền tiểu học
INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
VALUES (1, 'ENG-TD-01', N'English for Kids - Tiền tiểu học', 15, 12, 10, '2025-01-25', '2025-03-25', 'SATURDAY,SUNDAY', '09:00-11:00', N'P.102 - Tầng 1 - Thủ Đức', 'ACTIVE');

GO

-- Cập nhật CURRENT_STUDENTS counter
UPDATE CLASSES SET CURRENT_STUDENTS = 17 WHERE CODE = 'IELTS-GV-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 12 WHERE CODE = 'IELTS-GV-02';
UPDATE CLASSES SET CURRENT_STUDENTS = 22 WHERE CODE = 'MATH-GV-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 18 WHERE CODE = 'MATH-GV-02';
UPDATE CLASSES SET CURRENT_STUDENTS = 14 WHERE CODE = 'VAN-GV-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 13 WHERE CODE = 'CODE-TB-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 16 WHERE CODE = 'CODE-TB-02';
UPDATE CLASSES SET CURRENT_STUDENTS = 15 WHERE CODE = 'VAN-TB-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 11 WHERE CODE = 'ENG-TB-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 18 WHERE CODE = 'MATH-TB-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 14 WHERE CODE = 'PHY-TD-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 13 WHERE CODE = 'CHEM-TD-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 16 WHERE CODE = 'IELTS-TD-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 15 WHERE CODE = 'BIO-TD-01';
UPDATE CLASSES SET CURRENT_STUDENTS = 10 WHERE CODE = 'ENG-TD-01';

GO

PRINT 'Successfully inserted 15 classes from schedule data!';
PRINT 'Note: Make sure COURSES (ID 1-5) and TEACHERS (ID 1-15) exist before running this script.';
