-- =================================================================
-- DMT EDUCATION SYSTEM - INSERT SCHEDULE CLASSES DATA
-- =================================================================
-- Script import dữ liệu lịch học từ mock data
-- =================================================================

USE DMT_EDUCATION_SYSTEM;
GO

-- Đảm bảo các SUBJECTS tồn tại
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'IELTS')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('IELTS', N'IELTS', N'Khóa học IELTS quốc tế');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'MATH')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('MATH', N'Toán học', N'Các khóa học Toán');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'VAN')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('VAN', N'Ngữ văn', N'Các khóa học Văn');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'CODE')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('CODE', N'Lập trình', N'Các khóa học Lập trình');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'PHY')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('PHY', N'Vật lý', N'Các khóa học Vật lý');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'CHEM')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('CHEM', N'Hóa học', N'Các khóa học Hóa học');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'BIO')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('BIO', N'Sinh học', N'Các khóa học Sinh học');
IF NOT EXISTS (SELECT 1 FROM SUBJECTS WHERE CODE = 'ENG')
  INSERT INTO SUBJECTS (CODE, NAME, DESCRIPTION) VALUES ('ENG', N'Tiếng Anh', N'Các khóa học Tiếng Anh giao tiếp');
GO

-- Đảm bảo các COURSES tồn tại
-- GÒ VẤP COURSES
IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'IELTS-FOUND')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'IELTS-FOUND', N'IELTS Intensive - Foundation', N'Khóa học IELTS nền tảng cho người mới bắt đầu', 9, 27, 3500000, 'BEGINNER'
  FROM SUBJECTS WHERE CODE = 'IELTS';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'IELTS-70')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'IELTS-70', N'IELTS Target 7.0+', N'Khóa học cao cấp cho học viên mục tiêu 7.0-8.0', 9, 27, 4500000, 'ADVANCED'
  FROM SUBJECTS WHERE CODE = 'IELTS';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'MATH-THCS')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'MATH-THCS', N'Toán Tư duy THCS', N'Phát triển tư duy toán học cho học sinh THCS', 9, 27, 3000000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'MATH';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'MATH-THPT')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'MATH-THPT', N'Toán THPT - Luyện thi THPT QG', N'Ôn thi THPT Quốc gia môn Toán', 12, 36, 4200000, 'ADVANCED'
  FROM SUBJECTS WHERE CODE = 'MATH';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'VAN-THCS')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'VAN-THCS', N'Văn THCS - Nâng cao kỹ năng viết', N'Nâng cao kỹ năng viết văn nghị luận', 9, 18, 2800000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'VAN';

-- QUẬN 12 COURSES
IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'CODE-PYTHON')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'CODE-PYTHON', N'Lập trình Junior - Python Foundation', N'Khóa học lập trình Python cho thiếu niên', 12, 24, 4800000, 'BEGINNER'
  FROM SUBJECTS WHERE CODE = 'CODE';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'CODE-WEB')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'CODE-WEB', N'Lập trình Web - HTML/CSS/JavaScript', N'Học xây dựng website từ A-Z', 12, 36, 5500000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'CODE';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'VAN-THPT')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'VAN-THPT', N'Tiếng Việt nâng cao THPT', N'Ôn luyện Ngữ văn THPT', 12, 36, 3600000, 'ADVANCED'
  FROM SUBJECTS WHERE CODE = 'VAN';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'ENG-BIZ')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'ENG-BIZ', N'English Communication - Business', N'Tiếng Anh giao tiếp thương mại', 9, 27, 4200000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'ENG';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'MATH-TH')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'MATH-TH', N'Toán tư duy sáng tạo Tiểu học', N'Phát triển tư duy toán học cho tiểu học', 9, 18, 2600000, 'BEGINNER'
  FROM SUBJECTS WHERE CODE = 'MATH';

-- QUẬN 3 COURSES
IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'PHY-THPT')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'PHY-THPT', N'Khoa học tự nhiên - Vật lý THPT', N'Vật lý THPT với phương pháp thực hành', 12, 24, 3800000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'PHY';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'CHEM-THPT')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'CHEM-THPT', N'Hóa học THPT - Nâng cao', N'Hóa học nâng cao THPT', 12, 36, 4000000, 'ADVANCED'
  FROM SUBJECTS WHERE CODE = 'CHEM';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'IELTS-JUNIOR')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'IELTS-JUNIOR', N'IELTS Junior - Khởi đầu tự tin', N'IELTS dành cho học sinh THCS-THPT', 12, 36, 3800000, 'BEGINNER'
  FROM SUBJECTS WHERE CODE = 'IELTS';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'BIO-THPT')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'BIO-THPT', N'Sinh học THPT - Ôn thi THPT QG', N'Sinh học THPT toàn diện', 12, 36, 3600000, 'INTERMEDIATE'
  FROM SUBJECTS WHERE CODE = 'BIO';

IF NOT EXISTS (SELECT 1 FROM COURSES WHERE CODE = 'ENG-KIDS')
  INSERT INTO COURSES (SUBJECT_ID, CODE, NAME, DESCRIPTION, DURATION_WEEKS, TOTAL_SESSIONS, PRICE, LEVEL)
  SELECT ID, 'ENG-KIDS', N'English for Kids - Tiền tiểu học', N'Tiếng Anh cho trẻ 5-7 tuổi', 9, 18, 3200000, 'BEGINNER'
  FROM SUBJECTS WHERE CODE = 'ENG';
GO

-- Lấy ID của các campus
DECLARE @govapId INT = (SELECT ID FROM CAMPUSES WHERE CODE = 'govap');
DECLARE @quan12Id INT = (SELECT ID FROM CAMPUSES WHERE CODE = 'quan12');
DECLARE @quan3Id INT = (SELECT ID FROM CAMPUSES WHERE CODE = 'quan3');

-- Lấy ID của teacher đầu tiên (nếu có)
DECLARE @teacherId INT = (SELECT TOP 1 ID FROM TEACHERS);
IF @teacherId IS NULL SET @teacherId = 1;

-- Insert CLASSES cho Gò Vấp
IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'IELTS-GV-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'IELTS-GV-01', N'IELTS Intensive - Foundation', @teacherId, @govapId, 20, 17, '2025-01-15', '2025-03-15', 'THU2,THU4,THU6', '18:30-20:30', N'P.201 - Tầng 2', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'IELTS-FOUND';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'IELTS-GV-02')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'IELTS-GV-02', N'IELTS Target 7.0+', @teacherId, @govapId, 15, 12, '2025-01-20', '2025-03-20', 'THU3,THU5,THU7', '19:00-21:00', N'P.305 - Tầng 3', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'IELTS-70';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'MATH-GV-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'MATH-GV-01', N'Toán Tư duy THCS', @teacherId, @govapId, 25, 22, '2025-01-18', '2025-03-18', 'THU3,THU5,THU7', '17:00-19:00', N'P.102 - Tầng 1', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'MATH-THCS';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'MATH-GV-02')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'MATH-GV-02', N'Toán THPT - Luyện thi THPT QG', @teacherId, @govapId, 20, 18, '2025-01-15', '2025-04-15', 'THU2,THU4,CN', '19:30-21:30', N'P.401 - Tầng 4', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'MATH-THPT';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'VAN-GV-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'VAN-GV-01', N'Văn THCS - Nâng cao kỹ năng viết', @teacherId, @govapId, 18, 14, '2025-01-22', '2025-03-22', 'THU2,THU4', '18:00-20:00', N'P.203 - Tầng 2', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'VAN-THCS';

-- Insert CLASSES cho Quận 12
IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'CODE-Q12-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'CODE-Q12-01', N'Lập trình Junior - Python Foundation', @teacherId, @quan12Id, 15, 13, '2025-01-20', '2025-04-20', 'THU3,THU5', '19:00-21:00', N'Lab 1 - Tầng 3', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'CODE-PYTHON';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'CODE-Q12-02')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'CODE-Q12-02', N'Lập trình Web - HTML/CSS/JavaScript', @teacherId, @quan12Id, 18, 16, '2025-01-15', '2025-04-15', 'THU2,THU4,THU6', '18:30-20:30', N'Lab 2 - Tầng 3', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'CODE-WEB';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'VAN-Q12-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'VAN-Q12-01', N'Tiếng Việt nâng cao THPT', @teacherId, @quan12Id, 20, 15, '2025-01-20', '2025-04-20', 'THU2,THU4,THU6', '17:30-19:30', N'P.205 - Tầng 2', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'VAN-THPT';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'ENG-Q12-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'ENG-Q12-01', N'English Communication - Business', @teacherId, @quan12Id, 15, 11, '2025-01-18', '2025-03-18', 'THU3,THU5,THU7', '18:00-20:00', N'P.302 - Tầng 3', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'ENG-BIZ';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'MATH-Q12-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'MATH-Q12-01', N'Toán tư duy sáng tạo Tiểu học', @teacherId, @quan12Id, 20, 18, '2025-01-25', '2025-03-25', 'THU7,CN', '08:30-10:30', N'P.101 - Tầng 1', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'MATH-TH';

-- Insert CLASSES cho Quận 3
IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'PHY-Q3-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'PHY-Q3-01', N'Khoa học tự nhiên - Vật lý THPT', @teacherId, @quan3Id, 18, 14, '2025-01-25', '2025-04-25', 'THU2,THU4', '18:00-20:00', N'Lab Vật lý - Tầng 2', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'PHY-THPT';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'CHEM-Q3-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'CHEM-Q3-01', N'Hóa học THPT - Nâng cao', @teacherId, @quan3Id, 16, 13, '2025-01-22', '2025-04-22', 'THU3,THU5,THU7', '19:00-21:00', N'Lab Hóa - Tầng 3', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'CHEM-THPT';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'IELTS-Q3-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'IELTS-Q3-01', N'IELTS Junior - Khởi đầu tự tin', @teacherId, @quan3Id, 20, 16, '2025-01-25', '2025-04-25', 'THU3,THU5,THU7', '16:00-18:00', N'P.401 - Tầng 4', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'IELTS-JUNIOR';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'BIO-Q3-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'BIO-Q3-01', N'Sinh học THPT - Ôn thi THPT QG', @teacherId, @quan3Id, 18, 15, '2025-01-20', '2025-04-20', 'THU2,THU4,CN', '18:30-20:30', N'P.205 - Tầng 2', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'BIO-THPT';

IF NOT EXISTS (SELECT 1 FROM CLASSES WHERE CODE = 'ENG-Q3-01')
  INSERT INTO CLASSES (COURSE_ID, CODE, NAME, TEACHER_ID, CAMPUS_ID, CAPACITY, CURRENT_STUDENTS, START_DATE, END_DATE, SCHEDULE_DAYS, SCHEDULE_TIME, CLASSROOM, STATUS)
  SELECT c.ID, 'ENG-Q3-01', N'English for Kids - Tiền tiểu học', @teacherId, @quan3Id, 12, 10, '2025-01-25', '2025-03-25', 'THU7,CN', '09:00-11:00', N'P.102 - Tầng 1', 'ACTIVE'
  FROM COURSES c WHERE c.CODE = 'ENG-KIDS';
GO

-- Xem kết quả
SELECT 
  c.ID, c.CODE, c.NAME, c.CLASSROOM, c.SCHEDULE_DAYS, c.SCHEDULE_TIME,
  c.CAPACITY, c.CURRENT_STUDENTS, c.STATUS,
  cp.NAME as CAMPUS_NAME,
  co.NAME as COURSE_NAME
FROM CLASSES c
LEFT JOIN CAMPUSES cp ON c.CAMPUS_ID = cp.ID
LEFT JOIN COURSES co ON c.COURSE_ID = co.ID
ORDER BY cp.SORT_ORDER, c.CODE;
GO

PRINT N'=== ĐÃ INSERT DỮ LIỆU CLASSES CHO 3 CƠ SỞ ===';
GO
